SportsStore.Ui/Controllers/AdminController.cs
namespace SportsStore.Ui.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Core.Contracts;

    public class AdminController : Controller
    {
        private IProductRepository _productRepository;

        public AdminController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public ActionResult Index()
        {
            return View(_productRepository.Products.ToList());
        }

        public ActionResult Create()
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            throw new NotImplementedException();
        }

        public ActionResult Delete(int id)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection form)
        {
            throw new NotImplementedException();
        }

        public ViewResult Edit(int productId)
        {
            var product = _productRepository.Products.First(p => p.ProductId == productId);

            return View(product);
        }

        [HttpPost]
        public ActionResult Edit(int productId, FormCollection form)
        {
            throw new NotImplementedException();
        }
    }
}

SportsStore.Ui/Controllers/BasketController.cs
namespace SportsStore.Ui.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Core.Contracts;
    using Core.Models.Entities;
    using Core.Models.ViewModels;

    public class BasketController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly IOrderSubmitter _orderSubmitter;

        public BasketController(IProductRepository productRepository, IOrderSubmitter orderSubmitter)
        {
            _productRepository = productRepository;
            _orderSubmitter = orderSubmitter;
        }

        public ViewResult Index(Basket basket, string returnUrl)
        {
            return View(new BasketIndexViewModel { Basket = basket, ReturnUrl = returnUrl });
        }

        public ActionResult AddToBasket(Basket basket, int productId, string returnUrl)
        {
            var product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            basket.AddItem(product, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public ActionResult RemoveFromBasket(Basket basket, int productId, string returnUrl)
        {
            var product = _productRepository.Products.FirstOrDefault(p => p.ProductId == productId);
            basket.RemoveLine(product);

            return RedirectToAction("Index", new { returnUrl });
        }

        [ChildActionOnly]
        public PartialViewResult Summary(Basket basket)
        {
            return PartialView("BasketSummary", basket);
        }

        public ViewResult CheckOut()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult CheckOut(Basket basket, ShippingDetails shippingDetails)
        {
            // Empty baskets can't be checked out
            if (basket.Lines.Count == 0)
            {
                ModelState.AddModelError("Basket", "Sorry, your basket is empty!");
            }

            if (ModelState.IsValid)
            {
                _orderSubmitter.SubmitOrder(basket, shippingDetails);
                basket.Clear();

                return View("Completed");
            }

            return View(shippingDetails);
        }
    }
}

SportsStore.Ui/Controllers/NavigationController.cs
namespace SportsStore.Ui.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using System.Web.Routing;
    using Core.Contracts;
    using Core.Models.ViewModels;

    public class NavigationController : Controller
    {
        private readonly IProductRepository _productRepository;

        public NavigationController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        [ChildActionOnly]
        public PartialViewResult Menu(string category)
        {
            Func<string, NavigationLink> makeLink = categoryName => new NavigationLink
            {
                Text = categoryName ?? "Home", RouteValues = new RouteValueDictionary(new
                {
                    controller = "Products", action = "List", category = categoryName, page = 1
                }),
                IsSelected = (category == null && categoryName == null) ||
                             (!string.IsNullOrWhiteSpace(categoryName) && !string.IsNullOrWhiteSpace(category) &&
                              categoryName.ToLower() == category.ToLower())
            };

            // Add "Home" to the start of the list
            var navigationLinks = new List<NavigationLink>
            {
                makeLink(null)
            };

            var categories = _productRepository.Products.Select(product => product.Category);
            foreach (var categoryName in categories.Distinct().OrderBy(c => c))
            {
                navigationLinks.Add(makeLink(categoryName));
            }

            return PartialView(navigationLinks);
        }
    }
}

SportsStore.Ui/Controllers/ProductsController.cs
namespace SportsStore.Ui.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Core.Contracts;
    using Core.Models.ViewModels;

    public class ProductsController : Controller
    {
        private readonly IProductRepository _productRepository;
        public int PageSize = 4;

        public ProductsController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            var productsToShow = string.IsNullOrWhiteSpace(category)
                                     ? _productRepository.Products
                                     : _productRepository.Products.Where(product => product.Category.ToLower() ==
                                                                                    category.ToLower());

            var viewModel = new ProductsListViewModel
            {
                Products = productsToShow.OrderBy(product => product.ProductId).Skip((page - 1) * PageSize)
                                         .Take(PageSize).ToList(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = productsToShow.Count()
                },
                CurrentCategory = category
            };

            return View(viewModel);
        }
    }
}

SportsStore.Ui/Views/Admin/Edit.cshtml
@model SportsStore.Core.Models.Entities.Product
@{
    ViewBag.Title = "Edit Product - " + Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>

@using (Html.BeginForm())
{
    @Html.EditorForModel()

    <button type="submit" class="btn btn-success">Save</button> @Html.ActionLink("Cancel and return to list", "Index")
}

SportsStore.Ui/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Core.Models.Entities.Product>
@{
    ViewBag.Title = "All Products";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>All Products</h1>

@if (Model.Any())
{
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Price</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var product in Model)
            {
                <tr>
                    <td>@product.ProductId</td>
                    <td>@Html.ActionLink(product.Name, "Edit", new {product.ProductId})</td>
                    <td>@product.Price.ToString("c")</td>
                    <td>
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductID", product.ProductId)
                            <button type="submit" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-remove"></span> Delete</button>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
        
        <p>@Html.ActionLink("Add a new product", "Create")</p>
    </div>
}

SportsStore.Ui/Views/Basket/BasketSummary.cshtml
@model SportsStore.Core.Models.Entities.Basket

@if (Model.Lines.Any())
{
    <div class="pull-right text-right">
        <p><strong>Your basket:</strong> @Model.Lines.Sum(l => l.Quantity) items
        <br/><a href="@Url.Action("Index", "Basket")"><span class="glyphicon glyphicon-shopping-cart"></span> Go to basket</a></p>
    </div>
}

SportsStore.Ui/Views/Basket/CheckOut.cshtml
@model SportsStore.Core.Models.Entities.ShippingDetails
@{
    ViewBag.Title = "Sports Store - Check out";
}

<h2>Check out now</h2>
<p>Please enter your details and we'll ship your goods right away!</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()

    <h3>Ship to</h3>
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <h3>Address</h3>
    <div class="form-group">
        @Html.LabelFor(m => m.AddressLine1)
        @Html.TextBoxFor(m => m.AddressLine1, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AddressLine1)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AddressLine2)
        @Html.TextBoxFor(m => m.AddressLine2, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AddressLine2)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.AddressLine3)
        @Html.TextBoxFor(m => m.AddressLine3, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.AddressLine3)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.City)
        @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.City)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.County)
        @Html.TextBoxFor(m => m.County, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.County)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Postcode)
        @Html.TextBoxFor(m => m.Postcode, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Postcode)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Country)
        @Html.TextBoxFor(m => m.Country, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Country)
    </div>

    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.GiftWrap) @Html.DisplayNameFor(m => m.GiftWrap)
        </label>
    </div>

    <button type="submit" class="btn btn-primary">Complete order</button>
}

SportsStore.Ui/Views/Basket/Completed.cshtml
@{
    ViewBag.Title = "Sports Store: Order Submitted";
}

<h2>Thanks!</h2>

<p>Thank you for placing your order. We'll ship your goods as soon as possible.</p>

SportsStore.Ui/Views/Basket/Index.cshtml
@model SportsStore.Core.Models.ViewModels.BasketIndexViewModel
@{
    ViewBag.Title = "Sports Store - Your Basket";
}

<h2>Your Basket</h2>

<table class="table table-responsive">
    <thead>
    <tr>
        <th>Quantity</th>
        <th>Item</th>
        <th>Price</th>
        <th>Subtotal</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var basketLine in Model.Basket.Lines)
    {
        <tr>
            <td>@basketLine.Quantity</td>
            <td>@basketLine.Product.Name</td>
            <td>@basketLine.Product.Price.ToString("c")</td>
            <td>@((basketLine.Quantity * basketLine.Product.Price).ToString("c"))</td>
            <td>
                @using (Html.BeginForm("RemoveFromBasket", "Basket"))
                {
                    @Html.Hidden("ProductId", basketLine.Product.ProductId)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                }
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="4">Total:</td>
        <td>@Model.Basket.CalculateTotalValue().ToString("c")</td>
    </tr>
    </tfoot>
</table>

<p>
    <a href="@Model.ReturnUrl" class="btn btn-default">Continue shopping</a>
    <a href="@Url.Action("CheckOut")" class="btn btn-primary">Check out now</a>
</p>

SportsStore.Ui/Views/Navigation/Menu.cshtml
@model IEnumerable<SportsStore.Core.Models.ViewModels.NavigationLink>

@if (Model != null && Model.Any())
{
    <nav class="hidden-sm">
        <ul class="nav nav-pills nav-stacked">
            @foreach (var link in Model)
            {
                <li class="@(link.IsSelected ? "active" : null)">@Html.RouteLink(link.Text, link.RouteValues)</li>
            }
        </ul>
    </nav>
}

SportsStore.Ui/Views/Products/List.cshtml
@model SportsStore.Core.Models.ViewModels.ProductsListViewModel
@{
    ViewBag.Title = Model.CurrentCategory ?? "All Products";
}

<div class="row">
    <h1>Products</h1>

    @foreach (var product in Model.Products)
    {
        Html.RenderPartial("ProductSummary", product);
    }
    
    <nav class="pull-right">
        @Html.FormattedPageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
    </nav>
    
</div>

SportsStore.Ui/Views/Shared/ProductSummary.cshtml
@model SportsStore.Core.Models.Entities.Product

<div class="item">
    <h3>@Model.Name</h3>
    @Model.Description
    <h4>@Model.Price.ToString("c")</h4>
    
    @using (Html.BeginForm("AddToBasket", "Basket"))
    {
        @Html.HiddenFor(x => x.ProductId)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add to basket</button>
    }
</div>

SportsStore.Ui/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewBag.Title</title>
    <link href="~/Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <div class="page-header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1>Sports Store <small>Administration</small></h1>
                    </div>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-3">
                Menu here
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/Assets/js/jquery.min.js"></script>
    <script src="~/Assets/js/bootstrap.min.js"></script>
</body>
</html>

SportsStore.Ui/Views/Shared/_Layout.cshtml
@using SportsStore.Ui.Controllers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>Sports Store - Admin - @ViewBag.Title</title>
    <link href="~/Assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Assets/css/styles.css" rel="stylesheet" />
</head>
<body>
<div class="container">
    @*<div class="row">
        <div class="col-md-12">*@
            <div class="page-header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <h1>Sports Store</h1>
                        </div>
                        <div class="col-md-6">
                            @if (!(ViewContext.Controller is BasketController))
                            {
                                Html.RenderAction("Summary", "Basket");
                            }
                        </div>
                    </div>
                </div>
                
            </div>
        @*</div>
    </div>*@
    <div class="row">
        <div class="col-md-3">
            @{Html.RenderAction("Menu", "Navigation");}
        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>
    
<script src="~/Assets/js/jquery.min.js"></script>
<script src="~/Assets/js/bootstrap.min.js"></script>
</body>
</html>